highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyllt.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Chris Turner's Resume
name: Abdulhamid M. Mousa
email: Abdulhamid97mousa@gmail.com
website: https://www.abdulhamid97mousa.tk/
website_full: https://www.abdulhamid97mousa.tk/
github: Abdulhamid97Mousa
twitter: HAMID97MOUSA
address:
  street: 顺义区裕龙一区9号楼3单元502
  postcode: 101300
  city: Beijing
  country: China

# needed for travis-ci build
exclude: [vendor]
