highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyllt.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Abdulhamid's Resume
name: Abdulhamid Mousa
email: Abdulhamid97mousa@gmail.com
email_full: mailto:Abdulhamid97mousa@gmail.com
website: github.com/Abdulhamid97Mousa/Abdulhamid97Mousa.github.io
website_full: github.com/Abdulhamid97Mousa/Abdulhamid97Mousa.github.io
github: github.com/Abdulhamid97Mousa
twitter: twitter.com/HAMID97MOUSA
tel: +86 130 5136 2167
tel_full: tel:+86 130 5136 2167
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
